
# Build configuration
schema_version: 2

services:
  - type: web
    name: juliaydavid
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    disks:
      - name: uploads
        mountPath: /opt/render/project/src/uploads
        sizeGB: 1 # El tamaño mínimo para el plan gratuito
